services:
  sniper:
    image: piotrostr/pump-rs
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .env:/.env
      - ./FAST.json:/FAST.json
      - ./auth.json:/auth.json
    command: ["./pump-rs", "snipe-portal", "--lamports", "20000000"]
    environment:
      - RUST_LOG=info
  seller:
    image: piotrostr/pump-rs
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .env:/.env
      - ./FAST.json:/FAST.json
      - ./auth.json:/auth.json
    command: ["./pump-rs", "seller"]
